AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec'
  NewCops: enable
  TargetRubyVersion: 2.6

# Gemspec/RequireMFA:
#   Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
