source 'https://rubygems.org'

gem 'jekyll', "~> 4.3.2"
# gem 'nokogumbo', '=2.0.3'
# gem 'sprockets', '~> 3.7'
# gem 'webrick'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll_all_collections', path: '../'
  gem 'jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_plugin_logger'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debase', '0.2.5.beta2', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'ruby-debug-ide', require: false
end
